### ISSUE TITLE
请问有支持es6版本的么

### ISSUE THREAD

**Issue by dhlolo** [mustime/minipbjs#1]
如题

**Comment by dhlolo** [comment]
还有个小问题：
![image](https://user-images.githubusercontent.com/50065494/153990386-37cd989b-5176-49b0-b9eb-91edb09ebf77.png)
这里$root[type]，如果type是'foo.Foo'类型应该取不到吧

**Comment by mustime** [comment]
> 还有个小问题： ![image](https://user-images.githubusercontent.com/50065494/153990386-37cd989b-5176-49b0-b9eb-91edb09ebf77.png) 这里$root[type]，如果type是'foo.Foo'类型应该取不到吧

hi, 你是read碰到报错了吗？
麻烦提供一下具体可供复现的proto文件供测试（最好尽量精简）。

另外这个项目有一段时间没有使用了，ES6的支持我回顾一下稍后答复

**Comment by dhlolo** [comment]
> 

> > 还有个小问题： ![image](https://user-images.githubusercontent.com/50065494/153990386-37cd989b-5176-49b0-b9eb-91edb09ebf77.png) 这里$root[type]，如果type是'foo.Foo'类型应该取不到吧
> 
> hi, 你是read碰到报错了吗？ 麻烦提供一下具体可供复现的proto文件供测试（最好尽量精简）。
> 
> 另外这个项目有一段时间没有使用了，ES6的支持我回顾一下稍后答复

目前并没有碰到问题，只是对实现比较好奇，因为最近在处理类似的问题，但发现到message级别就不能再用静态的思维去抽象了。看了下，似乎你在$root上额外挂了路径和对应Message序列化的实例，我比较奇怪，因为是顺序指定，那如果$root.msg.MessageA中需要使用$root.msg.MessagB，但在执行MessageB的`!inner && ($root[path + '.' + key] = parent[key]);`挂载前就使用了$root上挂的encode或者decode函数，理论上会有问题，但是你的写法生成的代码似乎规避了这个问题。
![image](https://user-images.githubusercontent.com/50065494/154063781-c54cd595-92da-414b-8eac-14653148c539.png)

**Comment by dhlolo** [comment]
另外我看了下，似乎目前codeGen里还没有实现verify，在序列化的时候，最好加上对jsObject的校验，不然有可能会造成编解码的问题。

**Comment by mustime** [comment]
> > 
> 
> > > 还有个小问题： ![image](https://user-images.githubusercontent.com/50065494/153990386-37cd989b-5176-49b0-b9eb-91edb09ebf77.png) 这里$root[type]，如果type是'foo.Foo'类型应该取不到吧
> > 
> > 
> > hi, 你是read碰到报错了吗？ 麻烦提供一下具体可供复现的proto文件供测试（最好尽量精简）。
> > 另外这个项目有一段时间没有使用了，ES6的支持我回顾一下稍后答复
> 
> 目前并没有碰到问题，只是对实现比较好奇，因为最近在处理类似的问题，但发现到message级别就不能再用静态的思维去抽象了。看了下，似乎你在$root上额外挂了路径和对应Message序列化的实例，我比较奇怪，因为是顺序指定，那如果$root.msg.MessageA中需要使用$root.msg.MessagB，但在执行MessageB的`!inner && ($root[path + '.' + key] = parent[key]);`挂载前就使用了$root上挂的encode或者decode函数，理论上会有问题，但是你的写法生成的代码似乎规避了这个问题。 ![image](https://user-images.githubusercontent.com/50065494/154063781-c54cd595-92da-414b-8eac-14653148c539.png)

其实你说的这个情况不会出现，以你提到的例子为例：
1. 可以看到生成出来的代码中，注释 `// set prototypes and collect inner namespace for map fields` 处下方对prototype的填充，实际上不会对非基础类型的数据填充，确切来说会进入最后一个else里的处理，也就是固定对 MessageA.prototype.field_messageB = null（这也是 `pbjs` 里的固定处理）；
2. 创建 MessageA 实例绑定到 $root 时调用的 `Constructor` 同理；
3. `reader`、`writer` 的调用只会发生在各功能函数中，也就是 `encode`/`decode` 的时候 $root 已经加载完毕了。

**Comment by mustime** [comment]
> 另外我看了下，似乎目前codeGen里还没有实现verify，在序列化的时候，最好加上对jsObject的校验，不然有可能会造成编解码的问题。

这个可以有，当初项目仅考虑到我们公司的几个微信小游戏项目需求，因此并没有完全地支持一些`pbjs`上原有的特性。

**Comment by mustime** [comment]
另外我对比了下 `pbjs` 里对 `--es6` 的处理，似乎就是体力活... 改 let/const 之类的。
我个人其实对 JS 使用和理解不算深入，所以也好奇以这个生成出来的胶水代码而言，有什么情况下是必须，或者说用 es6 比 es5 更佳？

**Comment by dhlolo** [comment]
> 

感谢解答。我之前是把prototype也封装进函数里，才有这个问题。

**Comment by dhlolo** [comment]
> 另外我对比了下 `pbjs` 里对 `--es6` 的处理，似乎就是体力活... 改 let/const 之类的。 我个人其实对 JS 使用和理解不算深入，所以也好奇以这个生成出来的胶水代码而言，有什么情况下是必须，或者说用 es6 比 es5 更佳？

这一点我的理解是：esm是较新的，更利于静态分析的模块化规范，理论上应该更有助于梳理MessageFactory的逻辑，从而使脱离codeGen，而使用语言本身的反射特性来实现的可能性更高一些，当然也会更优雅。

**Comment by dhlolo** [comment]
今天在使用minipb生成的代码中碰到了两个问题:
 - 生成的decode方法需要加入id in payloads的判断，因为会出现field_number不连续的情况：
![image](https://user-images.githubusercontent.com/50065494/154217074-8b6560be-a116-4c15-bec7-62527e53aee7.png)
  - 在使用DownStreamdecode方法时，遇到了下面的问题，不知道是不是和我的改动有关，报错在Reader.prototype.bytes中
![image](https://user-images.githubusercontent.com/50065494/154216751-04131d80-68f6-43f2-bfb1-50ea0c03e631.png)
![image](https://user-images.githubusercontent.com/50065494/154218027-45cbb87a-e3c7-44a5-9ffa-520b309dc9da.png)

**Comment by mustime** [comment]
> 今天在使用minipb生成的代码中碰到了两个问题:
> 
> * 生成的decode方法需要加入id in payloads的判断，因为会出现field_number不连续的情况：
>   ![image](https://user-images.githubusercontent.com/50065494/154217074-8b6560be-a116-4c15-bec7-62527e53aee7.png)
> * 在使用DownStreamdecode方法时，遇到了下面的问题，不知道是不是和我的改动有关，报错在Reader.prototype.bytes中
>   ![image](https://user-images.githubusercontent.com/50065494/154216751-04131d80-68f6-43f2-bfb1-50ea0c03e631.png)
>   ![image](https://user-images.githubusercontent.com/50065494/154218027-45cbb87a-e3c7-44a5-9ffa-520b309dc9da.png)

fieldId 不连续的情况应该也是没问题的才对，可以见 [tests/syntax/syntax_proto2.proto:L18](https://github.com/mustime/pbjs-mini/blob/main/tests/syntax/syntax_proto2.proto#L18) 的测试例子。具体我试下用你这个 message 样例 decode 看看。

**Comment by dhlolo** [comment]
用proto3试试呢，我这边用的是proto3

**Comment by mustime** [comment]
@dhlolo 
Hi, 你上面提供的 Downstream message结构正常在生成过程中应该是会报错的，因为定义了相同的key `com`（id: 1 & 6 处）。
另外我刚刚更新了一个版本，修复了之前历史遗留的64位整形的转换问题，而且我把你提供的样例修改后放到 tests 中，测试运行都ok了，你可以 `npm install -g minipbjs` 更新再试试。

**Comment by dhlolo** [comment]
> @dhlolo Hi, 你上面提供的 Downstream message结构正常在生成过程中应该是会报错的，因为定义了相同的key `com`（id: 1 & 6 处）。 另外我刚刚更新了一个版本，修复了之前历史遗留的64位整形的转换问题，而且我把你提供的样例修改后放到 tests 中，测试运行都ok了，你可以 `npm install -g minipbjs` 更新再试试。

因为涉及公司的字段，所以截取的时候没有注意到有两个重复的，实际上1和6是不重复的，感谢~

**Comment by dhlolo** [comment]
> @dhlolo Hi, 你上面提供的 Downstream message结构正常在生成过程中应该是会报错的，因为定义了相同的key `com`（id: 1 & 6 处）。 另外我刚刚更新了一个版本，修复了之前历史遗留的64位整形的转换问题，而且我把你提供的样例修改后放到 tests 中，测试运行都ok了，你可以 `npm install -g minipbjs` 更新再试试。

publish的時候似乎沒有添加dist，而把src發了出去
![image](https://user-images.githubusercontent.com/50065494/154398356-6b9bc291-eb22-4bcc-b008-c624f8541543.png)

**Comment by mustime** [comment]
> > @dhlolo Hi, 你上面提供的 Downstream message结构正常在生成过程中应该是会报错的，因为定义了相同的key `com`（id: 1 & 6 处）。 另外我刚刚更新了一个版本，修复了之前历史遗留的64位整形的转换问题，而且我把你提供的样例修改后放到 tests 中，测试运行都ok了，你可以 `npm install -g minipbjs` 更新再试试。
> 
> publish的時候似乎沒有添加dist，而把src發了出去 ![image](https://user-images.githubusercontent.com/50065494/154398356-6b9bc291-eb22-4bcc-b008-c624f8541543.png)

my bad.. try again

**Comment by dhlolo** [comment]
![image](https://user-images.githubusercontent.com/50065494/154399809-a085330f-400c-4d7c-b20b-a25af130f5fe.png)
我自己在全局node_modules build了一下，然後~。~

**Comment by mustime** [comment]
> ![image](https://user-images.githubusercontent.com/50065494/154399809-a085330f-400c-4d7c-b20b-a25af130f5fe.png) 我自己在全局node_modules build了一下，然後~。~

这个是运行时没有 protobuf.util.Long 定义了，如果你希望64整型也统一用 js Number 表示的话，要在命令行里加 `minipbjs --force-number <anything else>`。之前 Long 的支持不完善没有加，默认相当于强制了 `--force-number`，现在按照原 pbjs 的规则了。

**Comment by dhlolo** [comment]
ok，感謝，又報了這個錯。
![image](https://user-images.githubusercontent.com/50065494/154401442-a49420e1-a463-4188-80bf-18a7238ebe59.png)
不過這個地方id in payload的條件應該是需要的，
![image](https://user-images.githubusercontent.com/50065494/154401539-e4c9c242-aeb4-425d-b478-f3d680a21ab1.png)

**Comment by dhlolo** [comment]
> > 今天在使用minipb生成的代码中碰到了两个问题:
> > 
> > * 生成的decode方法需要加入id in payloads的判断，因为会出现field_number不连续的情况：
> >   ![image](https://user-images.githubusercontent.com/50065494/154217074-8b6560be-a116-4c15-bec7-62527e53aee7.png)
> > * 在使用DownStreamdecode方法时，遇到了下面的问题，不知道是不是和我的改动有关，报错在Reader.prototype.bytes中
> >   ![image](https://user-images.githubusercontent.com/50065494/154216751-04131d80-68f6-43f2-bfb1-50ea0c03e631.png)
> >   ![image](https://user-images.githubusercontent.com/50065494/154218027-45cbb87a-e3c7-44a5-9ffa-520b309dc9da.png)
> 
> fieldId 不连续的情况应该也是没问题的才对，可以见 [tests/syntax/syntax_proto2.proto:L18](https://github.com/mustime/pbjs-mini/blob/main/tests/syntax/syntax_proto2.proto#L18) 的测试例子。具体我试下用你这个 message 样例 decode 看看。

就是這個問題，我看test裏似乎只有encode沒有decode

**Comment by mustime** [comment]
@dhlolo 

tests/issues/test.js 里有这个的测试样例，我这边跑 `npm test` 是ok的。
关于需要 `payloads[id]` 这个报错还真没遇到过，不过综合两个报错来看，估计是旧数据中存在的fieldId数据，在新的已经被移除后的proto中进行decode导致的。

**Comment by dhlolo** [comment]
> tests/issues/test.js

有可能，不過我加了id in payloads就會有RangeError，而采用pbjs自己產生的static文件，就是不會報錯的

**Comment by mustime** [comment]
> > tests/issues/test.js
> 
> 有可能，不過我加了id in payloads就會有RangeError，而采用pbjs自己產生的static文件，就是不會報錯的

我测试了，就是这个问题，我fix一下。

**Comment by mustime** [comment]
@dhlolo 麻烦再更新测试一下

**Comment by dhlolo** [comment]
感谢，测试下来确实没什么问题了~

**Comment by mustime** [comment]
Nice, 感谢你的使用反馈 👏
另外关于 verify 和 es6/commonjs 等wrapper 的处理，我分别开了issue #2 和 #3，可以关注更新。

**Comment by dhlolo** [comment]
> Nice, 感谢你的使用反馈 👏 另外关于 verify 和 es6/commonjs 等wrapper 的处理，我分别开了issue #2 和 #3，可以关注更新。

因为项目中需要，所以准备提个veriry的PR，试着看了下你的代码，encode的递归设计还是很精巧 👍

**Comment by mustime** [comment]
> 因为项目中需要，所以准备提个veriry的PR，试着看了下你的代码，encode的递归设计还是很精巧 👍

欢迎！commit 中标记 "#2" 即可 👏🏻
