### ISSUE TITLE
 希望能提供cli使用方式

### ISSUE THREAD

**Issue by doerme** [mustime/minipbjs#6]
希望能提供 cli的使用方式  兼容protobufjs/cli/pbjs

**Comment by mustime** [comment]
你可以看看 [`cli/index.js`](https://github.com/mustime/minipbjs/blob/main/cli/index.js). 实际上 minipbjs 用的就是 `protobufjs/cli/pbjs`，兼容相关命令参数的。
[README](https://github.com/mustime/minipbjs/blob/main/README.zh-CN.md#%E7%94%9F%E6%88%90js%E4%BB%A3%E7%A0%81) 里也有具体命令行参数使用说明。
