### ISSUE TITLE
Don't assume node_module pathing in CLI

### ISSUE THREAD

**Issue by Aghassi** [mustime/minipbjs#7]
https://github.com/mustime/minipbjs/blob/97b245f4e7a3ac029ad5f18a9613ccffb25af7cc/cli/index.js#L76

This sort of logic is not necessary and can be broken easily in workspaces.

The better way to do this is just to use `require.resolve` since this is nodejs. `require.resolve` will pull the nearest version and then expand the path to the bin of the library you need and run it using the standard module resolution process.

Would you be open to a contribution to replace this logic so that it works out of box in more edge cases?

**Comment by mustime** [comment]
Thanks @Aghassi 
You're right. I will be appreciated it if you could help me fix it.

**Comment by Aghassi** [comment]
created a PR. I think it works, the tests pass. I didn't do much testing beyond that.
